services:
  itp-postgres:
    image: postgres:17.5-bullseye
    container_name: itp-postgres
    environment:
      POSTGRES_USER: itpusr
      POSTGRES_PASSWORD: itp@168
    ports:
      - "5168:5432"
    volumes:
      - ./init_scripts/postgres_init.sql:/docker-entrypoint-initdb.d/postgres_init.sql
      - itp-postgres-vol:/var/lib/postgresql/data
    networks:
      - itp-net

volumes:
  itp-postgres-vol:

networks:
  itp-net:
    external: true
